version: '3.8'

services:
  postgres:
    build: ./postgres/
    environment:
      POSTGRES_DB: ${PG_DB}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWD}
    restart: always
    networks:
      - rest-svc-network
    volumes:
      - pg-data:/var/lib/postgresql/data
      - pg-logs:/var/log/postgresql/
    ports:
      - "5432:5432"
  backend:
    build: ./
    restart: always
    depends_on:
      - postgres
    networks:
      - rest-svc-network
    ports:
      - "4000:4000"
    environment:
      PG_HOST: postgres

networks:
  rest-svc-network:
    driver: bridge
volumes:
  pg-data:
  pg-logs: