version: '3.8'

services:
  postgres:
    build: ./postgres/
    environment:
      POSTGRES_DB: ${PG_DB}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWD}
    networks:
      - rest-svc-network
    ports:
      - "5432:5432"
  backend:
    build: ./
    depends_on:
      - postgres
    networks:
      - rest-svc-network
    ports:
      - "4000:4000"
    environment:
      PG_HOST: postgres

networks:
  rest-svc-network:
    driver: bridge