on:
  pull_request:
    branches:
      - master
jobs:
  run-tests:
    runs-on: ubuntu-22.04

    name: test - ${{ matrix.test-command.name}}
    strategy:
      fail-fast: false
      matrix:
        node-version: [ 22.x ]
        test-command:
          - name: users main
            command: test/users.e2e.spec.ts
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Setup .env
        run: cp ".env.example" ".env"

      - name: Run service
        run: npm start &

      - name: Run test ${{ matrix.test-command.name }}
        run: npm test -- ${{ matrix.test-command.command }}