on:
  pull_request:
    branches:
      - master
jobs:
  run-tests:
    runs-on: ubuntu-22.04

    services:
      postgres17:
        image: postgres:17-alpine
        env:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: passwd
          POSTGRES_DB: rest-db
        ports:
          - 5432:5432

    name: test - ${{ matrix.test-command.name}}
    strategy:
      fail-fast: false
      matrix:
        node-version: [ 22.x ]
        test-command:
          - name: users auth
            command: auth/users.e2e.spec.ts
          - name: tracks auth
            command: auth/tracks.e2e.spec.ts
          - name: artists auth
            command: auth/artists.e2e.spec.ts
          - name: albums auth
            command: auth/albums.e2e.spec.ts
          - name: favourites auth
            command: auth/favorites.e2e.spec.ts
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Setup .env
        run: cp ".env.example" ".env"

      - name: Run migrations
        run: npm run typeorm:migration:run

      - name: Run service
        run: npm start &

      - name: Run test ${{ matrix.test-command.name }}
        run: npx cross-env TEST_MODE=auth jest --testPathPattern ${{ matrix.test-command.command }}